//resdecode remo
//resconvert Kurumma
//resconvert Codrac
//resconvert Coyot
//resconvert ST9
//resconvert Yotta
//resconvert Sunset
//resconvert Naxas
//resconvert Ninja
//resconvert Teg
//resconvert Whisper
resconvert Zed